package com.example.WebAppPayments.controller.command;

public enum CommandName {

    LOGIN,
    LOGOUT,
    REGISTERNEWUSER,
    GETUSERS,
    BLOCKUSER,
    UNBLOCKUSER,

    CHOOSELOCALE,

    GETCARDS,
    EXTENDCARDVALIDDATE,

    GETACCOUNTS,

    GETPAYMENTS,

    // other pages
    GOTOPROFILEPAGE,
    GOTOUSERSPAGE,
    GOTOACCOUNTPAGE,
    GOTOCARDSPAGE,
    GOTONEWPAYMENTPAGE,
    GOTOPAYMENTPAGE,
    GOTOCOMPLETEDPAYMENTPAGE,
    //

    GOTOMAINPAGE,
    GOTOREGISTERPAGE,
    GOTOLOGINPAGE,
    GOTOCONTACTSPAGE,
    GOTOABOUTPAGE,

    UPDATEUSERINFO,
    ADDNEWACCOUNT,
    ADDNEWCARD,
    ADDNEWPAYMENT,

    GETPROFILEINFO

}
